### ISSUE TITLE
Version 0.0.5 Not Available on Jitpack

### ISSUE THREAD

**Issue by daniel-cook** [VictorAlbertos/Jolyglot#10]
I'm trying to upgrade from 0.0.3 to 0.0.5 but Gradle is unable to resolve the library, as if this version is not available on Jitpack. I get the following error when trying to synce Gradle `Failed to resolve: com.github.VictorAlbertos.Jolyglot:jackson:0.0.5`

**Comment by VictorAlbertos** [comment]
There was a compile error in the `auto-value` module that stopped the build before building the `jackson` artifact. It is fixed now, please use: `com.github.VictorAlbertos.Jolyglot:jackson:0.0.6`
