### ISSUE TITLE
Transitive dependencies 

### ISSUE THREAD

**Issue by FilipStojanovskiWt** [VictorAlbertos/Jolyglot#11]
With update from 0.0.3 to 0.0.5 and even 0.0.6 version there are missing transitive dependencies that we are expecting to be there like the Types class from common module and in my case the jackson library (com.fasterxml.jackson package) is missing. Is this expected behavior?
 - if no I think the problem is in the build.gradle script instead of using implementation it should be api (the replacement of compile) and the script for building the lib should include all the dependencies
 - if yes how to resolve this issue and another questions is if I'm using different version of the jackson library will Jolyglot library work?

**Comment by VictorAlbertos** [comment]
> we are expecting to be there like the Types class from common 

As far as I remember the `Types` class was never meant to be part of this library API and that the fact that was transitively exposed was more kind of an accident. In any case, you can keep using it just by adding the common module dependency to your project. 

`implementation 'com.github.VictorAlbertos.common:0.0.6'
`
> Is this expected behavior?

Yes, as I prefer to avoid exposing transitively dependencies that I'm not going to update frequently. 

> if yes how to resolve this issue

Just add to your project the jackson dependency.  

> if I'm using different version of the jackson library will Jolyglot library work

It should work, but if you want to be sure just use the same that it's using Jolyglot: 
`implementation com.google.code.gson:gson:2.8.6`

**Comment by FilipStojanovskiWt** [comment]
Sorry for the late response, for the part with transitively dependencies I think it is great solution, I've already tried and it's working. Unfortunately I cannot resolve the common library, and that is still issue for me. Can you check it once again?

**Comment by VictorAlbertos** [comment]
Based on the [Jitpack logs](https://jitpack.io/com/github/VictorAlbertos/Jolyglot/0.0.6/build.log ) the `common` artifact was published: 

```
Build artifacts:
com.github.VictorAlbertos.Jolyglot:gson:0.0.6
com.github.VictorAlbertos.Jolyglot:gson_auto_value:0.0.6
com.github.VictorAlbertos.Jolyglot:jackson:0.0.6
com.github.VictorAlbertos.Jolyglot:moshi:0.0.6
com.github.VictorAlbertos.Jolyglot:api:0.0.6
com.github.VictorAlbertos.Jolyglot:fastjson:0.0.6
com.github.VictorAlbertos.Jolyglot:common:0.0.6
```

I think I wrote it wrong in my previous message, you should add the dependency as such:

`implementation 'com.github.VictorAlbertos.Jolyglot:common:0.0.6'`

**Comment by FilipStojanovskiWt** [comment]
Now it's working, many thanks for the help.
